/* The Instruments room: one page per instrument.
   low/high are the WRITTEN range (what the player reads), as note names; sounds = semitones from written
   to sounding pitch (−2 for B♭ instruments, −12 for an octave lower). exam = the instrument's name in the
   repertoire data. Like the composer films, each starts as checked: false until the owner has checked it. */
window.INSTRUMENTS = [
  /* ---------- strings ---------- */
  { id: "violin", name: "Violin", family: "Strings", exam: "Violin", clefs: ["treble"], low: "G3", high: "E7", sounds: 0,
    how: "The bow (horsehair rubbed with rosin) or a finger makes the strings vibrate, and the hollow wooden body makes the sound bigger.",
    strings: "Four strings, tuned in 5ths: G D A E.",
    facts: ["It is the smallest and highest member of the orchestra's string family.", "Antonio Stradivari made violins in Cremona, Italy, around 1700; about 650 of his instruments survive.", "The leader of an orchestra is a violinist, who tunes the orchestra and works closely with the conductor."],
    famous: ["Vivaldi: The Four Seasons", "Bach: Partita No. 2 in D minor", "Mendelssohn: Violin Concerto in E minor"],
    quiz: { q: "What are the violin's four strings?", options: ["G D A E", "C G D A", "E A D G"], answer: 0 }, checked: false },
  { id: "viola", name: "Viola", family: "Strings", exam: "Viola", clefs: ["alto", "treble"], low: "C3", high: "E6", sounds: 0,
    how: "Like a violin, played with a bow, but a little bigger, with a darker, warmer sound.",
    strings: "Four strings, tuned in 5ths: C G D A, a 5th lower than the violin.",
    facts: ["It mainly reads the alto clef, where middle C is on the middle line.", "Mozart liked to play the viola when he played string quartets with friends.", "In an orchestra the violas usually sit between the second violins and the cellos."],
    famous: ["Mozart: Sinfonia Concertante, K. 364", "Berlioz: Harold in Italy", "Walton: Viola Concerto"],
    quiz: { q: "Which clef does the viola mainly read?", options: ["Treble", "Alto", "Bass"], answer: 1 }, checked: false },
  { id: "cello", name: "Cello", family: "Strings", exam: "Cello", clefs: ["bass", "tenor", "treble"], low: "C2", high: "A5", sounds: 0,
    how: "Played sitting down, with the instrument resting on a spike (the endpin) and held between the knees, and played with a bow.",
    strings: "Four strings, tuned in 5ths: C G D A, an octave below the viola.",
    facts: ["Its full name is violoncello.", "Bach's six suites for solo cello are among the most famous pieces for any instrument.", "Cellists read the bass clef, then the tenor clef and treble clef for high notes."],
    famous: ["Bach: Cello Suite No. 1 in G", "Saint-Saëns: The Swan", "Elgar: Cello Concerto"],
    quiz: { q: "Which clef does a cellist read most?", options: ["Bass", "Treble", "Alto"], answer: 0 }, checked: false },
  { id: "doublebass", name: "Double bass", family: "Strings", exam: "Double bass", clefs: ["bass", "tenor"], low: "E2", high: "G4", sounds: -12,
    how: "The biggest bowed string instrument. Players stand or sit on a high stool, and use a bow or pluck the strings (pizzicato), especially in jazz.",
    strings: "Four strings tuned in 4ths: E A D G, unlike the other strings, which are tuned in 5ths.",
    facts: ["It sounds an octave lower than written, so its music doesn't need lots of leger lines.", "Saint-Saëns gave it the tune in ‘The Elephant’ from The Carnival of the Animals.", "In jazz the bass is usually plucked, keeping the beat and the harmony."],
    famous: ["Saint-Saëns: The Elephant", "Bottesini: Double Bass Concerto No. 2", "Dittersdorf: Double Bass Concerto in E"],
    quiz: { q: "How does the double bass sound compared with the written note?", options: ["An octave higher", "The same", "An octave lower"], answer: 2 }, checked: false },
  { id: "harp", name: "Harp", family: "Strings", exam: "Harp", clefs: ["treble", "bass"], low: "C1", high: "G7", sounds: 0,
    how: "The strings are plucked with the fingers of both hands. The thumb and first three fingers are used; the little finger isn't.",
    strings: "A concert (pedal) harp has 47 strings. The C strings are red and the F strings are dark, so players can find their place.",
    facts: ["It has seven pedals, one for each letter name. Each pedal makes every string of that name flat, natural or sharp.", "It reads two staves, like the piano.", "The harp is one of the oldest instruments: harps appear in pictures from ancient Egypt."],
    famous: ["Debussy: Danses sacrée et profane", "Handel: Harp Concerto in B♭", "Tchaikovsky: Waltz of the Flowers (cadenza)"],
    quiz: { q: "What do the harp's seven pedals do?", options: ["Make it louder", "Change strings to flat, natural or sharp", "Hold notes on"], answer: 1 }, checked: false },
  { id: "guitar", name: "Guitar", family: "Strings", exam: "Guitar", clefs: ["treble"], low: "E3", high: "B6", sounds: -12,
    how: "The strings are plucked or strummed with the fingers or a pick, while the other hand presses the strings against frets on the neck.",
    strings: "Six strings: E A D G B E.",
    facts: ["It sounds an octave lower than written.", "The classical guitar has nylon strings; the acoustic folk guitar usually has steel strings.", "The frets are metal strips that divide the neck into semitones."],
    famous: ["Tárrega: Recuerdos de la Alhambra", "Rodrigo: Concierto de Aranjuez", "Villa-Lobos: Prelude No. 1"],
    quiz: { q: "How many strings does a standard guitar have?", options: ["Four", "Six", "Twelve"], answer: 1 }, checked: false },
  /* ---------- woodwind ---------- */
  { id: "flute", name: "Flute", family: "Woodwind", exam: "Flute", clefs: ["treble"], low: "C4", high: "C7", sounds: 0,
    how: "The player blows across a hole in the head joint, and the air splits on its sharp edge. There is no reed.",
    facts: ["It is a woodwind instrument even though it is usually made of metal: it belongs to the family because of how the sound is made.", "Theobald Boehm designed the modern key system in the 1840s.", "The piccolo, the flute's little sister, sounds an octave higher than written."],
    famous: ["Debussy: Syrinx", "Bach: Badinerie from Orchestral Suite No. 2", "Mozart: Flute Concerto in G"],
    quiz: { q: "Why is the metal flute in the woodwind family?", options: ["Because of how its sound is made", "Because flutes used to be made of wood only", "Because it has keys"], answer: 0 }, checked: false },
  { id: "oboe", name: "Oboe", family: "Woodwind", exam: "Oboe", clefs: ["treble"], low: "Bb3", high: "A6", sounds: 0,
    how: "Two thin blades of cane (a double reed) vibrate against each other when the player blows between them.",
    facts: ["The orchestra tunes to the oboe's A before a concert.", "Oboists make or shape their own reeds by hand.", "In Prokofiev's Peter and the Wolf, the oboe plays the duck."],
    famous: ["Marcello: Oboe Concerto in D minor", "Mozart: Oboe Concerto in C", "Prokofiev: Peter and the Wolf (the duck)"],
    quiz: { q: "What kind of reed does the oboe use?", options: ["No reed", "A single reed", "A double reed"], answer: 2 }, checked: false },
  { id: "clarinet", name: "Clarinet", family: "Woodwind", exam: "Clarinet", clefs: ["treble"], low: "E3", high: "C7", sounds: -2,
    how: "A single reed vibrates against the mouthpiece. The tube is mostly cylindrical, which gives the clarinet its round, hollow low notes.",
    facts: ["The usual clarinet is in B♭: it sounds a tone lower than written. Orchestras also use the clarinet in A.", "Mozart wrote his Clarinet Concerto for his friend, the clarinettist Anton Stadler.", "In Peter and the Wolf, the clarinet plays the cat."],
    famous: ["Mozart: Clarinet Concerto in A", "Weber: Clarinet Concerto No. 1", "Gershwin: Rhapsody in Blue (opening)"],
    quiz: { q: "A clarinet in B♭ plays a written C. Which note sounds?", options: ["C", "B♭", "D"], answer: 1 }, checked: false },
  { id: "bassoon", name: "Bassoon", family: "Woodwind", exam: "Bassoon", clefs: ["bass", "tenor"], low: "Bb1", high: "E5", sounds: 0,
    how: "A double reed on a curved metal crook. Its tube is about 2.5 metres long, folded in half.",
    facts: ["It reads the bass clef, and the tenor clef for high notes.", "In Peter and the Wolf, the bassoon plays the grandfather.", "The contrabassoon sounds an octave lower still."],
    famous: ["Vivaldi: Bassoon concertos", "Mozart: Bassoon Concerto in B♭", "Dukas: The Sorcerer's Apprentice"],
    quiz: { q: "Which character does the bassoon play in Peter and the Wolf?", options: ["The bird", "The grandfather", "The wolf"], answer: 1 }, checked: false },
  { id: "saxophone", name: "Saxophone", family: "Woodwind", exam: "Saxophone", clefs: ["treble"], low: "Bb3", high: "F#6", sounds: -9,
    how: "A single reed on a mouthpiece, like the clarinet, on a cone-shaped brass body.",
    facts: ["Adolphe Sax invented it in the 1840s, and patented it in 1846.", "It is a woodwind instrument because it uses a reed, even though it is made of brass.", "The alto saxophone, the one most players start on, is in E♭ and sounds a major 6th lower than written."],
    famous: ["Glazunov: Saxophone Concerto", "Ravel: Boléro (solos)", "Debussy: Rhapsody for saxophone"],
    quiz: { q: "Who invented the saxophone?", options: ["Adolphe Sax", "Johann Sebastian Bach", "Theobald Boehm"], answer: 0 }, checked: false },
  { id: "recorder", name: "Recorder", family: "Woodwind", exam: "Recorder", clefs: ["treble"], low: "C4", high: "D6", sounds: 12,
    how: "The player blows into a beak-shaped mouthpiece that directs the air against a sharp edge, like a whistle.",
    facts: ["The descant recorder sounds an octave higher than written.", "In the Baroque period the treble (alto) recorder was a serious solo instrument: Bach, Handel and Telemann wrote for it.", "The family runs from the tiny sopranino to the great bass."],
    famous: ["Telemann: Recorder Concerto in C", "Handel: Recorder sonatas", "Vivaldi: Recorder Concerto in C, RV 443"],
    quiz: { q: "How does the descant recorder sound compared with the written note?", options: ["An octave higher", "The same", "An octave lower"], answer: 0 }, checked: false },
  /* ---------- brass ---------- */
  { id: "trumpet", name: "Trumpet", family: "Brass", exam: "Trumpet & cornet", clefs: ["treble"], low: "F#3", high: "C6", sounds: -2,
    how: "The player buzzes their lips into a cup-shaped mouthpiece. Three valves add extra tubing to reach the notes in between.",
    facts: ["The usual trumpet is in B♭: it sounds a tone lower than written.", "Haydn's Trumpet Concerto (1796) was written for a new keyed trumpet that could play every note.", "The cornet is a close relative with a mellower sound, the leading instrument of brass bands."],
    famous: ["Haydn: Trumpet Concerto in E♭", "Purcell: Trumpet Tune", "Clarke: Trumpet Voluntary"],
    quiz: { q: "How do brass players make the sound?", options: ["By buzzing their lips", "With a reed", "By blowing across a hole"], answer: 0 }, checked: false },
  { id: "horn", name: "Horn", family: "Brass", exam: "Horn", clefs: ["treble", "bass"], low: "F#3", high: "C6", sounds: -7,
    how: "Lip-buzzing, like all brass, through about 3.7 metres of coiled tubing. The player's right hand sits inside the bell to shape the sound.",
    facts: ["The horn in F sounds a perfect 5th lower than written.", "Mozart wrote four horn concertos, several for his friend Joseph Leutgeb.", "Before valves, horn players changed notes with their lips and hand alone."],
    famous: ["Mozart: Horn Concerto No. 4", "Strauss: Horn Concerto No. 1", "Tchaikovsky: Symphony No. 5 (slow movement solo)"],
    quiz: { q: "The horn in F reads a written C. Which note sounds?", options: ["F", "C", "G"], answer: 0 }, checked: false },
  { id: "trombone", name: "Trombone", family: "Brass", exam: "Trombone", clefs: ["bass", "tenor"], low: "E2", high: "F5", sounds: 0,
    how: "Instead of valves it has a slide. Moving the slide out to seven positions makes the tube longer and the note lower.",
    facts: ["In orchestras it reads the bass and tenor clefs at sounding pitch; in British brass bands it reads treble clef as a B♭ instrument.", "Beethoven made a famous entrance for trombones in the finale of his Fifth Symphony.", "The slide makes the trombone the one brass instrument that can glide smoothly between notes (a glissando)."],
    famous: ["Rimsky-Korsakov: Trombone Concerto", "Mozart: Requiem (Tuba mirum solo)", "Ravel: Boléro (solo)"],
    quiz: { q: "How does a trombonist change the note, apart from the lips?", options: ["Valves", "A slide", "Keys"], answer: 1 }, checked: false },
  { id: "euphonium", name: "Euphonium", family: "Brass", exam: "Euphonium & baritone", clefs: ["bass", "treble"], low: "E2", high: "Bb4", sounds: 0,
    how: "A tenor tuba with a wide conical bore and a warm, singing sound, played with valves.",
    facts: ["It is a star of brass bands and military bands.", "In brass bands it reads treble clef as a B♭ instrument, sounding a major 9th lower; in orchestras and wind bands it often reads bass clef at sounding pitch.", "Its name comes from Greek ‘euphonos’, meaning ‘sweet-voiced’."],
    famous: ["Holst: Mars, from The Planets (tenor tuba solo)", "Horovitz: Euphonium Concerto", "Sparke: Euphonium Concerto"],
    quiz: { q: "Where is the euphonium most often heard?", options: ["Brass and military bands", "String quartets", "Jazz big bands only"], answer: 0 }, checked: false },
  { id: "tuba", name: "Tuba", family: "Brass", exam: "Tuba", clefs: ["bass"], low: "D1", high: "F4", sounds: 0,
    how: "The biggest and lowest brass instrument, with a huge bell and a deep mouthpiece. It is played with valves.",
    facts: ["The bass tuba was patented in Berlin in 1835.", "Vaughan Williams wrote one of the first tuba concertos, in 1954.", "In orchestras it usually plays the bass line of the brass section."],
    famous: ["Vaughan Williams: Tuba Concerto", "Mussorgsky/Ravel: Bydło, from Pictures at an Exhibition", "Wagner: The Mastersingers overture"],
    quiz: { q: "Which is the lowest brass instrument in the orchestra?", options: ["Trombone", "Horn", "Tuba"], answer: 2 }, checked: false },
  /* ---------- keyboards ---------- */
  { id: "piano", name: "Piano", family: "Keyboard", exam: "Piano", clefs: ["treble", "bass"], low: "A0", high: "C8", sounds: 0,
    how: "Each key moves a felt hammer that hits the strings. The harder you press, the louder the note, which is why its full name is pianoforte (‘quiet-loud’).",
    facts: ["Bartolomeo Cristofori built the first pianos in Florence, around 1700.", "A modern piano has 88 keys: 52 white and 36 black.", "The right pedal lifts the dampers so the strings keep ringing."],
    famous: ["Beethoven: Für Elise", "Chopin: Nocturnes", "Debussy: Clair de lune"],
    quiz: { q: "What makes the sound on a piano?", options: ["Hammers hitting strings", "Plucked strings", "Air in pipes"], answer: 0 }, checked: false },
  { id: "organ", name: "Organ", family: "Keyboard", exam: "Organ", clefs: ["treble", "bass"], low: "C2", high: "C7", sounds: 0,
    how: "Air from a blower sounds pipes of different lengths and shapes. Stops choose which sets of pipes play, and the feet play a pedal keyboard.",
    facts: ["Large church organs can have thousands of pipes.", "Organ music is often written on three staves: two for the hands and one for the feet.", "Bach was famous in his lifetime above all as an organist."],
    famous: ["Bach: Toccata and Fugue in D minor", "Widor: Toccata from Symphony No. 5", "Saint-Saëns: ‘Organ’ Symphony"],
    quiz: { q: "What do organists play with their feet?", options: ["Nothing", "A pedal keyboard", "Drums"], answer: 1 }, checked: false },
  { id: "harpsichord", name: "Harpsichord", family: "Keyboard", exam: "Harpsichord", clefs: ["treble", "bass"], low: "F1", high: "F6", sounds: 0,
    how: "Each key lifts a jack with a small plectrum that plucks the string, so you can't play louder or softer by pressing harder.",
    facts: ["It was the main keyboard instrument of the Baroque period.", "Players change the sound with extra sets of strings (registers) and by adding ornaments.", "Domenico Scarlatti wrote 555 keyboard sonatas, many of them for harpsichord."],
    famous: ["Bach: Goldberg Variations", "Scarlatti: Sonatas", "Rameau: Pièces de clavecin"],
    quiz: { q: "How is the string sounded on a harpsichord?", options: ["Hit by a hammer", "Plucked", "Bowed"], answer: 1 }, checked: false },
  /* ---------- percussion and voice ---------- */
  { id: "timpani", name: "Timpani", family: "Percussion", exam: "Timpani", clefs: ["bass"], low: "D2", high: "A3", sounds: 0,
    how: "Large copper drums (kettledrums) played with soft-headed sticks. A pedal tightens or loosens the skin to tune each drum to a note.",
    facts: ["A timpanist usually plays a set of four drums, each tuned to a different note.", "They are tuned percussion: unlike most drums, they play definite pitches.", "In the scherzo of Beethoven's Ninth Symphony the timpani are tuned an octave apart, to two Fs."],
    famous: ["Haydn: ‘Drumroll’ Symphony No. 103", "Strauss: Also sprach Zarathustra (opening)", "Beethoven: Symphony No. 9"],
    quiz: { q: "How are timpani tuned?", options: ["With a pedal", "They can't be tuned", "By changing the stick"], answer: 0 }, checked: false },
  { id: "voice", name: "Voice", family: "Voice", exam: "Singing", clefs: ["treble", "bass"], low: "E2", high: "C6", sounds: 0,
    how: "Air from the lungs makes the vocal folds vibrate, and the throat, mouth and nose shape the sound.",
    facts: ["The four main voice types are soprano, alto, tenor and bass (SATB).", "Tenors read treble clef music an octave lower than written, often shown by a small 8 under the clef.", "Singing exams include songs in other languages, such as Italian, German and French."],
    famous: ["Handel: Messiah", "Schubert: songs", "Mozart: The Magic Flute"],
    quiz: { q: "What vibrates when you sing?", options: ["The vocal folds", "The tongue", "The teeth"], answer: 0 }, checked: false }
];
